# Generated by Django 2.1.1 on 2018-09-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
